AWSTemplateFormatVersion: 2010-09-09
Description: |
  Enable to create website templates with yaml file.
  
Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable to connect by using SSH and HTTP # Required
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0  

  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      KeyName: melisvirginiakeypair
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      UserData: 
        !Base64 
         #! /bin/bash
         sudo yum update -y
         sudo yum install httpd -y
         FOLDER="https://raw.githubusercontent.com/F4309melisavcilar/self-study/main/Project-101-kittens-carousel-static-website-ec2/static-web"
         cd /var/www/html
         wget ${FOLDER}/index.html
         wget ${FOLDER}/cat0.jpg
         wget ${FOLDER}/cat1.jpg
         wget ${FOLDER}/cat2.jpg
         wget ${FOLDER}/cat3.jpg
         systemctl start httpd
         systemctl enable httpd

      Tags:
        - Key: Name
          Value: !Sub Web Server ${AWS::StackName} StackName


Outputs:
  WebSiteUrl:
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServerHost.PublicDnsName
    Description: Kittens Carousel Application URL